import type {
  MachineDefinition,
  MemberDefinition,
  WeaponDefinition,
  EquipmentDefinition,
  SupplyDefinition,
  ProgressionNode,
  MissionDefinition,
  StoreOffer,
  ServiceChallenge,
  RewardCategory,
  MachineType,
} from './eva-types';

export const RULE_VERSION = 'eva-3.1-local.1';
export const IDS = {
  eva00: 'machine.rebuild.eva00.base',
  eva01: 'machine.rebuild.eva01.base',
  eva02: 'machine.rebuild.eva02.base',
  eva08: 'machine.rebuild.eva08.alpha',
  rei: 'member.rebuild.rei',
  shinji: 'member.rebuild.shinji',
  asuka: 'member.rebuild.asuka.shikinami',
  mari: 'member.rebuild.mari',
  misato: 'member.rebuild.misato',
  ritsuko: 'member.rebuild.ritsuko',
  maya: 'member.rebuild.maya',
} as const;
export const CAPACITIES = {
  1: { equipment: 1, skills: 1, driverSkills: 1, supportSkills: 1 },
  2: { equipment: 2, skills: 2, driverSkills: 2, supportSkills: 1 },
  3: { equipment: 3, skills: 3, driverSkills: 3, supportSkills: 2 },
} as const;
/** Local playtest values; no cash price is represented by the gold denominations. */
export const BALANCE = {
  status: 'local-playtest',
  licenseMultiplier: 1.5,
  supportRatio: 0.6,
  generalRatio: 0.1,
  winMultiplier: 1.2,
  upgrade: { 2: 1800, 3: 4200 },
  repairMaximum: { 1: 220, 2: 320, 3: 450 },
  recoverySilver: 160,
  initialSilver: 600,
  initialTickets: 3,
  pityThreshold: 9,
  proficiencyMax: 12000,
  proficiencyTier: 3000,
  resonanceProficiency: 1200,
  resonanceSorties: 3,
  masterySorties: 8,
  dataCosts: [0, 700, 1000, 1600, 2600, 3000],
  routeCosts: [800, 1300, 1900],
  duplicate: {
    machine: 30,
    driver: 24,
    support: 24,
    equipment: 10,
    cosmetic: 6,
    ammo: 0,
    consumable: 0,
  },
  exchange: {
    machine: 160,
    driver: 120,
    support: 100,
    equipment: 50,
    cosmetic: 30,
    ammo: 2,
    consumable: 6,
  },
  categoryProbability: {
    machine: 0.08,
    driver: 0.08,
    support: 0.06,
    equipment: 0.25,
    consumable: 0.2,
    ammo: 0.23,
    cosmetic: 0.1,
  },
  licenseDurationMs: 30 * 24 * 60 * 60 * 1000,
  battleHistoryLimit: 100,
  drawHistoryLimit: 100,
} as const;
const source = {
  sourceContinuity: 'Rebuild of Evangelion',
  sourceRefs: [
    'https://www.evangelion.jp/2_0/chara.html',
    'https://satellite.bandai-hobby.net/characters/eva.php',
  ],
  adaptationNote: '型号与人物来源为新剧场版；类型、技能、跨机驾驶与数值为本作原创改编。',
};
export const MACHINES: MachineDefinition[] = [
  {
    id: IDS.eva00,
    name: '零号机',
    description: '以屏障掩护和远距救援保持战线，追击与爆发较弱。',
    type: 'defense',
    tags: ['屏障', '掩护'],
    stats: { hp: 135, damageMult: 0.9, speedMult: 0.92, cooldownMult: 1, energyRegen: 5 },
    branches: ['guardian', 'phase-rescue'],
    weapons: ['weapon.rifle', 'weapon.cannon', 'weapon.twin'],
    melee: ['melee.spear', 'melee.blade'],
    asset: '/eva/battle-unit00.svg',
    ...source,
  },
  {
    id: IDS.eva01,
    name: '初号机',
    description: '利用承伤后的反击窗口与同步释放应对多种目标。',
    type: 'balance',
    tags: ['反击', '同步'],
    stats: { hp: 115, damageMult: 1, speedMult: 1, cooldownMult: 1, energyRegen: 5.5 },
    branches: ['counterattack', 'awakening'],
    weapons: ['weapon.rifle', 'weapon.twin', 'weapon.cannon'],
    melee: ['melee.blade', 'melee.spear'],
    asset: '/eva/battle-unit01.svg',
    ...source,
  },
  {
    id: IDS.eva02,
    name: '二号机',
    description: '推进近战与重装压制两条打法，爆发时需规划防护。',
    type: 'attack',
    tags: ['突击', '压制'],
    stats: { hp: 100, damageMult: 1.12, speedMult: 1.08, cooldownMult: 1, energyRegen: 5 },
    branches: ['assault', 'artillery'],
    weapons: ['weapon.rifle', 'weapon.twin', 'weapon.cannon'],
    melee: ['melee.blade', 'melee.spear'],
    asset: '/eva/battle-unit02.svg',
    ...source,
  },
  {
    id: IDS.eva08,
    name: '八号机 α',
    description: '标记弱点、供能与协同射击，需要队友兑现支援窗口。',
    type: 'support',
    tags: ['标记', '供能'],
    stats: { hp: 105, damageMult: 0.92, speedMult: 1.04, cooldownMult: 0.96, energyRegen: 6.5 },
    branches: ['fire-coordination', 'rescue-network'],
    weapons: ['weapon.rifle', 'weapon.cannon', 'weapon.twin'],
    melee: ['melee.blade', 'melee.spear'],
    asset: '/eva/battle-unit08.svg',
    ...source,
  },
];
const members: [string, string, 'driver' | 'support', MachineType[], string, string, string][] = [
  [
    IDS.rei,
    '绫波丽',
    'driver',
    ['defense', 'support'],
    IDS.eva00,
    'rei-precision',
    '冷静精确的援护；屏障成功保护后形成连接。',
  ],
  [
    IDS.shinji,
    '碇真嗣',
    'driver',
    ['balance'],
    IDS.eva01,
    'shinji-counter',
    '在受压后稳定同步，抓住反击与觉醒窗口。',
  ],
  [
    IDS.asuka,
    '式波·明日香',
    'driver',
    ['attack'],
    IDS.eva02,
    'asuka-drive',
    '推进衔接与近战决斗；火力分支强化持续压制。',
  ],
  [
    IDS.mari,
    '真希波·玛丽',
    'driver',
    ['support', 'attack'],
    IDS.eva08,
    'mari-mark',
    '标记转化与协同射击，灵活处理高威胁目标。',
  ],
  [
    IDS.misato,
    '葛城美里',
    'support',
    ['attack', 'balance'],
    IDS.eva02,
    'misato-command',
    '战术指令强化突破节奏，救援后恢复团队行动窗口。',
  ],
  [
    IDS.ritsuko,
    '赤木律子',
    'support',
    ['defense', 'balance'],
    IDS.eva01,
    'ritsuko-efficiency',
    '技术保障减少技能能耗，诊断目标薄弱部位。',
  ],
  [
    IDS.maya,
    '伊吹摩耶',
    'support',
    ['support', 'defense'],
    IDS.eva00,
    'maya-monitor',
    '同步监测与供能回收，保护窗口内改善恢复效率。',
  ],
];
export const MEMBERS: MemberDefinition[] = members.map(
  ([id, name, role, familiarTypes, resonanceMachineId, passive, description]) => {
    const slug = id.split('.').at(-1) === 'shikinami' ? 'asuka' : id.split('.').at(-1);
    return {
      id,
      name,
      role,
      familiarTypes,
      resonanceMachineId,
      passive,
      description,
      asset:
        slug === 'rei' || slug === 'asuka'
          ? `/assets/pilot-${slug}.png`
          : `/eva/portrait-${slug}.png`,
      ...source,
    };
  },
);
export const WEAPONS: WeaponDefinition[] = [
  {
    id: 'weapon.rifle',
    name: '托盘步枪',
    description: '稳定直线单发；标准弹持续可用。',
    kind: 'primary',
    ammo: ['ammo.precision', 'ammo.high-explosive', 'ammo.resonance'],
    behavior: 'rifle',
    range: 720,
    cooldown: 0.55,
    damage: 25,
  },
  {
    id: 'weapon.twin',
    name: '双联突击炮',
    description: '两条并行弹道形成近中距压制，单发伤害降低。',
    kind: 'primary',
    ammo: ['ammo.precision', 'ammo.high-explosive'],
    behavior: 'twin',
    range: 580,
    cooldown: 0.65,
    damage: 18,
  },
  {
    id: 'weapon.cannon',
    name: '蓄能精确炮',
    description: '装填较慢、贯穿一目标的高强度单发；射击短暂限制机动。',
    kind: 'primary',
    ammo: ['ammo.precision', 'ammo.resonance'],
    behavior: 'charge-cannon',
    range: 940,
    cooldown: 1.1,
    damage: 52,
  },
  {
    id: 'melee.blade',
    name: '高振动匕首',
    description: '近距快速斩击，便于推进后衔接。',
    kind: 'melee',
    ammo: [],
    behavior: 'blade',
    range: 65,
    cooldown: 0.75,
    damage: 42,
  },
  {
    id: 'melee.spear',
    name: '长柄振动矛',
    description: '较长直线穿刺，挥击间隔较长。',
    kind: 'melee',
    ammo: [],
    behavior: 'spear',
    range: 110,
    cooldown: 1.1,
    damage: 52,
  },
];
export const EQUIPMENT: EquipmentDefinition[] = [
  {
    id: 'equipment.pulse-coil',
    name: '脉冲增幅线圈',
    description: '武器与技能伤害 +10%。',
    category: 'ordinary',
    group: 'amplifier',
    machineIds: [],
    types: [],
    stats: { damageMult: 1.1 },
    price: 750,
    currency: 'silver',
  },
  {
    id: 'equipment.resonance-core',
    name: '共振火控核心',
    description: '伤害 +14%；与脉冲增幅线圈互斥。',
    category: 'ordinary',
    group: 'amplifier',
    machineIds: [],
    types: [],
    stats: { damageMult: 1.14 },
    price: 1200,
    currency: 'silver',
  },
  {
    id: 'equipment.composite-armor',
    name: '复合装甲片',
    description: '最大耐久 +15。',
    category: 'ordinary',
    group: 'armor',
    machineIds: [],
    types: [],
    stats: { hp: 15 },
    price: 600,
    currency: 'silver',
  },
  {
    id: 'equipment.at-lining',
    name: 'A.T. 缓冲衬层',
    description: '最大耐久 +25；有效吸收达到阈值后短时减伤。',
    category: 'ordinary',
    group: 'armor',
    machineIds: [],
    types: [],
    stats: { hp: 25 },
    passive: 'at-buffer',
    price: 1100,
    currency: 'silver',
  },
  {
    id: 'equipment.vector-thruster',
    name: '矢量推进模组',
    description: '移动速度 +10%。',
    category: 'ordinary',
    group: 'thruster',
    machineIds: [],
    types: [],
    stats: { speedMult: 1.1 },
    price: 800,
    currency: 'silver',
  },
  {
    id: 'equipment.sync-relay',
    name: '同步中继模块',
    description: '战术技能冷却缩短 8%；能量主动装置已迁至机体技能树。',
    category: 'ordinary',
    group: 'cooling',
    machineIds: [],
    types: [],
    stats: { cooldownMult: 0.92 },
    price: 950,
    currency: 'silver',
  },
  {
    id: 'equipment.fire-stabilizer',
    name: '火控稳定器',
    description: '连续三次有效命中后下一发获得稳定增益，有独立冷却。',
    category: 'ordinary',
    group: 'fire-stabilizer',
    machineIds: [],
    types: [],
    stats: { damageMult: 1.03 },
    passive: 'steady-hit',
    price: 1000,
    currency: 'silver',
  },
  {
    id: 'equipment.boost-recycler',
    name: '推进回收组件',
    description: '成功规避预警攻击后恢复少量同步能量。',
    category: 'ordinary',
    group: 'thruster',
    machineIds: [],
    types: [],
    stats: { energyRegen: 0.5 },
    passive: 'dodge-recycle',
    price: 1000,
    currency: 'silver',
  },
  {
    id: 'equipment.rescue-link',
    name: '救援协同组件',
    description: '完成有效救援后为双方生成短时屏障。',
    category: 'ordinary',
    group: 'rescue',
    machineIds: [],
    types: [],
    stats: { hp: 10 },
    passive: 'rescue-shield',
    price: 900,
    currency: 'silver',
  },
  {
    id: 'equipment.mastery-assault',
    name: '二号机突击精通组件',
    description: '二号机伤害 +12%；推进后首次近战恢复少量能量，受冷却约束。',
    category: 'mastery',
    group: 'amplifier',
    machineIds: [IDS.eva02],
    types: [],
    stats: { damageMult: 1.12 },
    passive: 'assault-recycle',
    price: 180,
    currency: 'gold',
  },
  {
    id: 'equipment.mastery-barrier',
    name: '零号机屏障精通组件',
    description: '零号机耐久 +28；有效保护队友后恢复少量同步能量。',
    category: 'mastery',
    group: 'armor',
    machineIds: [IDS.eva00],
    types: [],
    stats: { hp: 28 },
    passive: 'barrier-recycle',
    price: 180,
    currency: 'gold',
  },
  {
    id: 'equipment.mastery-counter',
    name: '初号机反击精通组件',
    description: '初号机耐久 +15；受击反击窗口内强化一次有效攻击。',
    category: 'mastery',
    group: 'counter',
    machineIds: [IDS.eva01],
    types: [],
    stats: { hp: 15 },
    passive: 'counter-focus',
    price: 180,
    currency: 'gold',
  },
  {
    id: 'equipment.mastery-support',
    name: '八号机协同精通组件',
    description: '八号机供能恢复 +0.8；队友兑现标记后恢复少量能量。',
    category: 'mastery',
    group: 'support-link',
    machineIds: [IDS.eva08],
    types: [],
    stats: { energyRegen: 0.8 },
    passive: 'mark-recycle',
    price: 180,
    currency: 'gold',
  },
];
export const AMMO: SupplyDefinition[] = [
  {
    id: 'ammo.precision',
    name: '精确弹',
    description: '单目标有效伤害提高；每次射击消耗一发。',
    price: 3,
    pack: 20,
    carryLimit: 60,
    behavior: 'precision',
    legacy: 'AP',
  },
  {
    id: 'ammo.high-explosive',
    name: '高爆弹',
    description: '命中后处理邻近集群；每次射击消耗一发。',
    price: 5,
    pack: 12,
    carryLimit: 40,
    behavior: 'explosive',
    legacy: 'HE',
  },
  {
    id: 'ammo.resonance',
    name: '共振弹',
    description: '削弱目标防护供后续攻击兑现；每次射击消耗一发。',
    price: 6,
    pack: 10,
    carryLimit: 30,
    behavior: 'resonance',
    legacy: 'HESH',
  },
];
export const CONSUMABLES: SupplyDefinition[] = [
  {
    id: 'consumable.repair',
    name: '维修包',
    description: '恢复 35 点当前耐久，不能超过上限。',
    price: 40,
    pack: 2,
    carryLimit: 3,
    behavior: 'repair',
  },
  {
    id: 'consumable.battery',
    name: '同步电池',
    description: '恢复 40 点同步能量，不能超过上限。',
    price: 35,
    pack: 2,
    carryLimit: 3,
    behavior: 'battery',
  },
  {
    id: 'consumable.barrier',
    name: '临时屏障发生器',
    description: '短时生成可吸收有限伤害的屏障。',
    price: 45,
    pack: 2,
    carryLimit: 3,
    behavior: 'barrier',
  },
];
export const COSMETICS = [
  {
    id: 'cosmetic.nerv-standard',
    name: 'NERV 标准识别',
    description: '标准机体识别纹样，无战斗属性。',
  },
  { id: 'cosmetic.dawn-stripe', name: '破晓识别带', description: '橙白机体识别带，无战斗属性。' },
  { id: 'cosmetic.night-watch', name: '夜间守望', description: '深蓝监视涂装，无战斗属性。' },
  { id: 'cosmetic.unit-safety', name: '全员归还', description: '全员存活资历纪念涂装。' },
  { id: 'cosmetic.route-veteran', name: '多面战术', description: '三条有效路线资历徽记。' },
  { id: 'cosmetic.rescue-veteran', name: '生命接力', description: '有效救援资历徽记。' },
  { id: 'cosmetic.guard-veteran', name: '守护之壁', description: '有效掩护资历徽记。' },
];
type MachineTheme = {
  names: string[];
  skills: string[];
  routeNames: string[][];
  routeEffects: string[][];
  routeStats: [Partial<MachineDefinition['stats']>, Partial<MachineDefinition['stats']>];
};
const machineThemes: Record<string, MachineTheme> = {
  [IDS.eva02]: {
    names: [
      '启动校准',
      '双联武装许可',
      '二级战斗整备',
      '突击系统整合',
      '三级战斗整备',
      '限制器释放许可',
    ],
    skills: ['barrage', 'assault'],
    routeNames: [
      ['近战突击路线', '推进与近战衔接', '兽化形式'],
      ['重武装路线', '火控与持续压制', '武装释放形式'],
    ],
    routeEffects: [
      ['assault-drive', 'assault-chain', 'beast'],
      ['artillery-stance', 'artillery-sustain', 'arsenal'],
    ],
    routeStats: [{ speedMult: 1.04 }, { damageMult: 1.04 }],
  },
  [IDS.eva00]: {
    names: [
      '启动校准',
      '精确援护许可',
      '二级屏障整备',
      '相位救援整合',
      '三级屏障整备',
      '守护系统释放',
    ],
    skills: ['barrier', 'phase'],
    routeNames: [
      ['坚守屏障路线', '定向拦截', '共鸣壁垒'],
      ['相位救援路线', '空间掩护', '救援波'],
    ],
    routeEffects: [
      ['guardian-stance', 'barrier-intercept', 'fortress'],
      ['phase-extension', 'phase-rescue', 'rescue-wave'],
    ],
    routeStats: [{ hp: 12 }, { cooldownMult: 0.96 }],
  },
  [IDS.eva01]: {
    names: [
      '启动校准',
      '多用途武装许可',
      '二级同步整备',
      '反击回路整合',
      '三级同步整备',
      '觉醒安全许可',
    ],
    skills: ['counter', 'awakening'],
    routeNames: [
      ['稳态反击路线', '损伤反馈', '反击释放'],
      ['同步觉醒路线', '能量积蓄', '觉醒释放'],
    ],
    routeEffects: [
      ['counter-stance', 'counter-charge', 'retaliation'],
      ['awakening-balance', 'awakening-charge', 'awakening-burst'],
    ],
    routeStats: [{ hp: 8 }, { energyRegen: 0.4 }],
  },
  [IDS.eva08]: {
    names: [
      '启动校准',
      '协同武装许可',
      '二级支援整备',
      '供能网络整合',
      '三级支援整备',
      '协同系统释放',
    ],
    skills: ['mark', 'energy-link'],
    routeNames: [
      ['协同火控路线', '标记转化', '精确协同齐射'],
      ['救援网络路线', '供能接力', '救援链接'],
    ],
    routeEffects: [
      ['mark-duration', 'marked-fire', 'precision-volley'],
      ['energy-transfer', 'rescue-network', 'rescue-link'],
    ],
    routeStats: [{ damageMult: 1.03 }, { energyRegen: 0.6 }],
  },
};
const effectDescriptions: Record<string, string> = {
  barrage: '短时双路弹幕持续射击，开火期间限制常规移动。',
  assault: '沿面向快速推进，为后续近战或掩护蓄能创造窗口。',
  beast: '进入短时近战兽化，期间停止常规远程射击。',
  arsenal: '强化持续火力释放，保持射击压制并承担机动限制。',
  barrier: '生成有限吸收容量的屏障，保护附近存活队友。',
  phase: '沿面向相位移动，抵达后生成短时屏障。',
  fortress: '延长队伍屏障并修复范围内有效损伤。',
  'rescue-wave': '向附近友军释放修复波，可救起倒地队友。',
  counter: '形成短时自护盾，并建立蓄能反击窗口。',
  retaliation: '强化自护与反击窗口，适合承接高威胁攻击。',
  awakening: '进入有限时间的同步释放状态，强化有效攻击。',
  'awakening-burst': '以较长同步释放窗口替换基础觉醒形式。',
  mark: '标记邻近高威胁目标，待队友命中兑现削弱与有效支援。',
  'energy-link': '向附近队友补充同步能量，实际被使用后才计支援贡献。',
  'precision-volley': '发起蓄能协同射击，适合与队友交叉火力或屏障掩护配合。',
  'rescue-link': '展开救援链接，修复范围内友军并救起倒地者。',
  'assault-drive': '提高当前突击路线的机动性，推进动作获得额外衔接收益。',
  'assault-chain': '推进中的近战获得额外伤害，形成推进—近战节奏。',
  'artillery-stance': '提高当前重装路线的火力属性。',
  'artillery-sustain': '延长当前弹幕压制时间，旧迁移配置还保留移动弹幕能力。',
  'guardian-stance': '增加当前守护路线的机体耐久。',
  'barrier-intercept': '增加屏障实际可吸收的伤害容量。',
  'phase-extension': '延长相位位移距离，方便跨越危险窗口。',
  'phase-rescue': '相位抵达后修复附近友军，并可救起倒地队友。',
  'counter-stance': '提高当前反击路线的耐久。',
  'counter-charge': '有效承伤后建立反击蓄能窗口。',
  'awakening-balance': '提高当前觉醒路线的同步能量恢复。',
  'awakening-charge': '低能量时加快同步恢复，准备下一次释放。',
  'mark-duration': '延长标记削弱窗口，为队友留出转化时间。',
  'marked-fire': '在当前标记路线中强化对已标记目标的协同命中。',
  'energy-transfer': '提高一次供能链接可转移的能量。',
  'rescue-network': '缩短基础救援等待，完成救援后提供短时保护。',
};
const node = (
  ownerId: string,
  suffix: string,
  name: string,
  extra: Partial<ProgressionNode> = {},
): ProgressionNode => ({
  id: `${ownerId}.${suffix}`,
  ownerId,
  name,
  description:
    (extra.effect && effectDescriptions[extra.effect]) ||
    (extra.grantsLevel
      ? `永久取得 ${extra.grantsLevel} 级整备资格；仍需另付作战经费才提高实际等级。`
      : extra.weaponIds?.length
        ? `取得${extra.weaponIds.map((id) => WEAPONS.find((w) => w.id === id)?.name || id).join('、')}使用授权。`
        : name),
  kind: 'main',
  cost: 0,
  requires: [],
  requiresAny: [],
  activationRequires: [],
  level: 1,
  ...extra,
});
export const NODES: ProgressionNode[] = MACHINES.flatMap((machine) => {
  const t = machineThemes[machine.id],
    id = machine.id;
  const main = t.names.map((name, i) =>
    node(id, `M0${i + 1}`, name, {
      cost: BALANCE.dataCosts[i],
      requires: i ? [`${id}.M0${i}`] : [],
      level: i >= 5 ? 3 : i >= 3 ? 2 : 1,
      ...(i === 0
        ? {
            slot: 'tactical' as const,
            effect: t.skills[0],
            weaponIds: ['weapon.rifle', machine.melee[0]],
          }
        : {}),
      ...(i === 1 ? { weaponIds: [machine.weapons[1]] } : {}),
      ...(i === 2 ? { grantsLevel: 2 as const } : {}),
      ...(i === 3
        ? {
            slot: 'tactical' as const,
            effect: t.skills[1],
            weaponIds: [machine.weapons[2], machine.melee[1]],
          }
        : {}),
      ...(i === 4 ? { grantsLevel: 3 as const } : {}),
    }),
  );
  const branches = machine.branches.flatMap((branch, b) =>
    [0, 1, 2].map((i) =>
      node(id, `${b === 0 ? 'A' : 'B'}${i + 1}`, t.routeNames[b][i], {
        kind: 'branch',
        branch,
        cost: BALANCE.routeCosts[i],
        requires: i
          ? [`${id}.${b === 0 ? 'A' : 'B'}${i}`, ...(i === 2 ? [`${id}.M06`] : [])]
          : [`${id}.M03`],
        activationRequires: i ? [`${id}.${b === 0 ? 'A' : 'B'}${i}`] : [],
        level: i === 2 ? 3 : 2,
        effect: t.routeEffects[b][i],
        ...(i === 0 ? { stats: t.routeStats[b] } : {}),
        ...(i === 2 ? { slot: 'tactical' as const, formGroup: 'release' } : {}),
      }),
    ),
  );
  return [
    ...main,
    ...branches,
    node(id, 'G1', '耐久与供能校准', {
      kind: 'general',
      cost: 600,
      requires: [`${id}.M01`],
      stats: { hp: 8, energyRegen: 0.3 },
    }),
    node(id, 'G2', '稳定性优化', {
      kind: 'general',
      cost: 1000,
      requires: [],
      requiresAny: [`${id}.G1`, `${id}.M04`],
      stats: { cooldownMult: 0.97 },
    }),
    node(id, 'relay', '同步中继启动', {
      cost: 700,
      requires: [`${id}.M03`],
      level: 2,
      slot: 'tactical',
      effect: 'sync-pulse',
      description: '恢复同步能量并形成短时自我屏障；迁移旧同步中继主动装置。',
    }),
  ];
});
NODES.push(
  node(IDS.eva02, 'legacy-guard', '旧式同步屏障', {
    level: 2,
    requires: [`${IDS.eva02}.M03`],
    slot: 'tactical',
    effect: 'barrier',
    migrationOnly: true,
    description: '仅历史迁移授予：保留旧同步屏障的队友掩护能力，仍占战术技能槽。',
  }),
  node(IDS.eva02, 'legacy-fortress', '旧式共鸣壁垒', {
    level: 3,
    requires: [`${IDS.eva02}.M05`, `${IDS.eva02}.legacy-guard`],
    slot: 'tactical',
    effect: 'fortress',
    formGroup: 'release',
    migrationOnly: true,
    description: '仅历史迁移授予：保留团队屏障和范围修复能力，替换旧式同步屏障并占战术槽。',
  }),
  node(IDS.eva00, 'legacy-missile', '旧式精确导弹', {
    level: 1,
    requires: [`${IDS.eva00}.M02`],
    slot: 'tactical',
    effect: 'precision-volley',
    migrationOnly: true,
    description: '仅历史迁移授予：保留旧导弹的主动射击入口与已学爆破效果，占战术槽。',
  }),
);
const personalNames: Record<string, string[]> = {
  [IDS.asuka]: ['独立操纵', '战术专精', '同步突破', '王牌资格', '近战决斗', '火力压制', '同步突击'],
  [IDS.rei]: ['冷静操纵', '援护专精', '守护同步', '守护者资格', '精确援护', '屏障救援', '守护链接'],
  [IDS.shinji]: [
    '同步接入',
    '稳态操纵',
    '反击同步',
    '觉醒适应',
    '稳态反击',
    '同步释放',
    '同步反击',
  ],
  [IDS.mari]: ['灵活操纵', '目标判读', '协同同步', '狙击适应', '标记兑现', '快速接力', '协同狙击'],
  [IDS.misato]: [
    '指令接入',
    '战场判断',
    '战术保障',
    '指挥资格',
    '集中突破',
    '救援指令',
    '战术保障共鸣',
  ],
  [IDS.ritsuko]: [
    '技术接入',
    '诊断专精',
    '系统保障',
    '研究资格',
    '能耗优化',
    '部位诊断',
    '技术保障共鸣',
  ],
  [IDS.maya]: [
    '监测接入',
    '同步判读',
    '链路保障',
    '监测资格',
    '同步监测',
    '供能回收',
    '同步监测共鸣',
  ],
};
const personalEffects: Record<string, [string, string]> = {
  [IDS.asuka]: [
    '提高推进中的近战收益，命中后建立衔接窗口。',
    '延长弹幕持续时间，并强化推进攻击衔接。',
  ],
  [IDS.rei]: ['提高站定射击的有效伤害。', '增加屏障吸收容量，并提高稳定射击收益。'],
  [IDS.shinji]: ['受到有效伤害后强化下一次反击。', '低能量时提高恢复，并强化受击反击窗口。'],
  [IDS.mari]: ['连续有效命中触发更长的标记削弱。', '机动输入时改善冷却推进，并增强标记窗口。'],
  [IDS.misato]: [
    '延长战术指令提供的下一次攻击窗口。',
    '完成救援后为双方生成短时屏障，同时强化指令窗口。',
  ],
  [IDS.ritsuko]: ['进一步降低战术技能同步能量消耗。', '提高部位有效伤害，并优化战术能耗。'],
  [IDS.maya]: [
    '屏障有效期间提高同步能量恢复。',
    '使用战术技能后按冷却回收少量同步能量，同时改善屏障期间恢复。',
  ],
};
for (const member of MEMBERS) {
  const id = member.id,
    names = personalNames[id],
    role = member.role,
    branches = role === 'driver' ? 3 : 2;
  for (let i = 0; i < 4; i++)
    NODES.push(
      node(id, `M0${i + 1}`, names[i], {
        cost: [0, 700, 1400, 2200][i],
        requires: i ? [`${id}.M0${i}`] : [],
        description: `${names[i]}：永久个人主线资格。`,
      }),
    );
  for (let b = 0; b < 2; b++)
    for (let i = 0; i < branches; i++)
      NODES.push(
        node(id, `${b ? 'B' : 'A'}${i + 1}`, `${names[4 + b]} ${i + 1}`, {
          kind: 'branch',
          branch: `member-${b ? 'b' : 'a'}`,
          cost: [550, 900, 1400][i],
          requires: [i ? `${id}.${b ? 'B' : 'A'}${i}` : `${id}.M02`],
          activationRequires: [],
          slot: role,
          effect: `${member.passive}-${b ? 'b' : 'a'}${i + 1}`,
          formGroup: `${id}.personal-route`,
          description: `${personalEffects[id][b]}第 ${i + 1} 档；只在装配时生效，同一人物分支方向互斥。`,
        }),
      );
  const generalCount = role === 'driver' ? 6 : 2;
  for (let i = 0; i < generalCount; i++)
    NODES.push(
      node(
        id,
        `G${i + 1}`,
        ['稳定操纵', '同步管理', '基础协同', '恢复习惯', '武器校准', '链路稳定'][i],
        {
          kind: 'general',
          cost: 400 + i * 150,
          requires: [i ? `${id}.G${i}` : `${id}.M01`],
          stats:
            i % 3 === 0 ? { hp: 2 } : i % 3 === 1 ? { energyRegen: 0.12 } : { cooldownMult: 0.99 },
          ...(role === 'driver' && (i === 2 || i === 5)
            ? {
                slot: 'driver' as const,
                stats: undefined,
                effect: i === 2 ? 'rescue-shield' : 'steady-hit',
                description:
                  i === 2
                    ? '需装入驾驶员特长槽：完成有效救援后，为双方提供短时屏障，与同名装备效果不重复叠加。'
                    : '需装入驾驶员特长槽：连续三次有效命中后，下一次射击获得稳定增益，与同名装备效果不重复叠加。',
              }
            : {}),
        },
      ),
    );
  NODES.push(
    node(id, 'resonance', names[6], {
      kind: 'resonance',
      cost: 1800,
      requires: [`${id}.M03`],
      slot: role,
      effect: `resonance-${member.passive}`,
      machineId: member.resonanceMachineId,
      proficiency: BALANCE.resonanceProficiency,
      sorties: BALANCE.resonanceSorties,
      description: `与${MACHINES.find((m) => m.id === member.resonanceMachineId)!.name}搭配，满足熟练度和 ${BALANCE.resonanceSorties} 次有效实战后解锁；占一个${role === 'driver' ? '特长' : '专长'}槽。`,
    }),
  );
  const masteryCount = role === 'driver' ? 4 : 2;
  for (let i = 0; i < masteryCount; i++)
    NODES.push(
      node(
        id,
        `X${i + 1}`,
        `${MACHINES.find((m) => m.id === member.resonanceMachineId)!.name}${i < 2 ? '稳态' : '火控'}精通 ${(i % 2) + 1}`,
        {
          kind: 'mastery',
          branch: i < 2 ? 'member-a' : 'member-b',
          cost: 2400 + i * 500,
          requires: [`${id}.M04`, ...(i % 2 ? [`${id}.X${i}`] : [])],
          machineId: member.resonanceMachineId,
          sorties: BALANCE.masterySorties + i * 2,
          stats: i < 2 ? { hp: 4, energyRegen: 0.15 } : { damageMult: 1.015 },
          description: '对明确目标机体的有限属性精通；只在已装个人分支方向匹配时生效。',
        },
      ),
    );
}
export const MISSIONS: MissionDefinition[] = [
  {
    id: 'mission.recovery',
    name: '后勤整备试验',
    description: '临时基础试验机清除目标，仅恢复少量作战经费；不扣个人库存，不产生损伤或培养数据。',
    campaignIndex: 0,
    objective: 'assault',
    levelCap: 1,
    stages: 1,
    dataPerStage: 0,
    silverPerStage: 160,
    condition: null,
    power: false,
    bossParts: false,
    scoring: { output: 400, protection: 100, support: 80, objective: 1, participation: 20 },
    version: RULE_VERSION,
  },
  ...Array.from({ length: 12 }, (_, i): MissionDefinition => ({
    id: `mission.campaign.${i + 1}`,
    name: `战役 ${i + 1}：${['破晓防线', '河流合唱', '虚空织者', '终末炽天使'][Math.floor(i / 3)]}`,
    description: `完成公开阶段目标并消灭威胁；标准弹持续可用，实际物资使用结算。${i % 3 === 2 ? 'Boss 任务通关获得 1 张补给申请券。' : '短关不发补给申请券。'}`,
    campaignIndex: i,
    objective: 'assault',
    levelCap: i < 3 ? 1 : i < 6 ? 2 : 3,
    stages: 1,
    dataPerStage: [4, 12, 60, 8, 18, 70, 12, 24, 80, 15, 30, 90][i],
    silverPerStage: [70, 100, 450, 90, 130, 520, 110, 160, 590, 140, 200, 680][i],
    condition: null,
    power: false,
    bossParts: false,
    scoring: { output: 800, protection: 150, support: 120, objective: 2, participation: 40 },
    version: RULE_VERSION,
    ticketsPerWin: i % 3 === 2 ? 1 : 0,
  })),
  {
    id: 'mission.assault',
    name: '目标突袭：棱镜解体',
    description: '破坏武装与防护部位，配合双人机制，在核心窗口完成突破；通关获得 1 张补给申请券。',
    campaignIndex: 2,
    objective: 'assault',
    levelCap: 3,
    stages: 3,
    dataPerStage: 20,
    silverPerStage: 220,
    condition: null,
    power: false,
    bossParts: true,
    scoring: { output: 1200, protection: 180, support: 150, objective: 3, participation: 60 },
    version: RULE_VERSION,
    ticketsPerWin: 1,
  },
  {
    id: 'mission.escort',
    name: '护送：生命接力',
    description:
      '保护运输目标通过可达路线，清除拦截；公开条件：增援频繁；通关获得 1 张补给申请券。',
    campaignIndex: 3,
    objective: 'escort',
    levelCap: 3,
    stages: 3,
    dataPerStage: 20,
    silverPerStage: 200,
    condition: 'reinforcements',
    power: false,
    bossParts: false,
    scoring: { output: 1000, protection: 180, support: 150, objective: 3, participation: 60 },
    version: RULE_VERSION,
    ticketsPerWin: 1,
  },
  {
    id: 'mission.defense',
    name: '阵地防御：同步堡垒',
    description:
      '维持防守区域，分担密集敌群与掩护任务；公开条件：敌群密集；通关获得 1 张补给申请券。',
    campaignIndex: 6,
    objective: 'defense',
    levelCap: 3,
    stages: 3,
    dataPerStage: 20,
    silverPerStage: 220,
    condition: 'dense-enemies',
    power: false,
    bossParts: false,
    scoring: { output: 1200, protection: 200, support: 150, objective: 3, participation: 60 },
    version: RULE_VERSION,
    ticketsPerWin: 1,
  },
  {
    id: 'mission.power-lab',
    name: '供能实验：脐带回路',
    description: '控制供能区域并经备用点执行突破；离线时仍可移动与标准射击；实验不发补给申请券。',
    campaignIndex: 0,
    objective: 'assault',
    levelCap: 3,
    stages: 1,
    dataPerStage: 6,
    silverPerStage: 90,
    condition: 'limited-power',
    power: true,
    bossParts: false,
    scoring: { output: 800, protection: 150, support: 120, objective: 2, participation: 40 },
    version: RULE_VERSION,
    ticketsPerWin: 0,
  },
];
export const CHALLENGES: ServiceChallenge[] = [
  {
    id: 'service.all-alive',
    name: '全员归还',
    description: '两名有效参战者存活完成三级任务。',
    kind: 'survival',
    target: 1,
    rewardId: 'cosmetic.unit-safety',
    minLevel: 3,
    archive: '本作原创档案：归还名单上，每一个名字都被保留。',
  },
  {
    id: 'service.three-routes',
    name: '多面战术',
    description: '用三条有有效战斗证据的不同机体路线完成同一任务。',
    kind: 'routes',
    target: 3,
    rewardId: 'cosmetic.route-veteran',
    minLevel: 1,
    archive: '本作原创档案：针对同一威胁，作战部留下了三份不同解法。',
  },
  {
    id: 'service.rescuer',
    name: '生命接力',
    description: '正式任务累计完成 10 次有效救援。',
    kind: 'rescue',
    target: 10,
    rewardId: 'cosmetic.rescue-veteran',
    minLevel: 1,
    archive: '本作原创档案：救援信号总能等来回答。',
  },
  {
    id: 'service.protector',
    name: '守护之壁',
    description: '正式任务累计替队友有效拦截 2000 点伤害。',
    kind: 'protection',
    target: 2000,
    rewardId: 'cosmetic.guard-veteran',
    minLevel: 1,
    archive: '本作原创档案：监测日志记录了每一次真正承担的冲击。',
  },
];
export const OFFERS: StoreOffer[] = [
  ...EQUIPMENT.map((e) => ({
    id: `offer.${e.id}`,
    name: e.name,
    description: e.description,
    currency: e.currency,
    price: e.price,
    category: 'equipment' as const,
    itemId: e.id,
    quantity: 1,
  })),
  ...[...AMMO, ...CONSUMABLES].map((e) => ({
    id: `offer.${e.id}`,
    name: e.name,
    description: `按件购买：${e.description}`,
    currency: 'silver' as const,
    price: e.price,
    category: (e.id.startsWith('ammo.') ? 'ammo' : 'consumable') as RewardCategory,
    itemId: e.id,
    quantity: 1,
  })),
  ...MACHINES.map((m) => ({
    id: `offer.${m.id}`,
    name: m.name,
    description: '永久所有权；从一级开始培养。',
    currency: 'gold' as const,
    price: 240,
    category: 'machine' as const,
    itemId: m.id,
    quantity: 1,
  })),
  ...MEMBERS.map((m) => ({
    id: `offer.${m.id}`,
    name: m.name,
    description: '永久成员所有权；不授予研究或熟练度。',
    currency: 'gold' as const,
    price: 160,
    category: m.role,
    itemId: m.id,
    quantity: 1,
  })),
  {
    id: 'offer.license.30d',
    name: '特别支援许可 · 30 天',
    description: '有效开局的经费与培养数据 +50%；续期保留剩余时间。',
    currency: 'gold',
    price: 120,
    category: 'license',
    itemId: 'license.support',
    quantity: 1,
    durationMs: BALANCE.licenseDurationMs,
  },
];
export const MODE_POLICIES = {
  operation: { growth: true, inventory: true, damage: true, service: true, silver: true },
  magi: { growth: false, inventory: false, damage: false, service: false, silver: false },
  tutorial: { growth: false, inventory: false, damage: false, service: false, silver: false },
  recovery: { growth: false, inventory: false, damage: false, service: false, silver: true },
} as const;
