'use strict';
const $=id=>document.getElementById(id),D=window.Dawn,P=window.Progression,E=window.Equipment,A=window.DAWN_ASSETS;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={Asuka:'明日香',Rei:'绫波丽'},slots={weapon:'武器增幅',armor:'机体装甲',module:'辅助模块'};
let user=null,profile=P.normalizeProfile(),screen='home',game=null,net=null,treeCharacter='Asuka',practiceCharacter='Asuka',selectedNode=null,trial=false,draft=[],trialBuilds={Asuka:[],Rei:[]},tutorial=null,rewarded=false,clock=0,last=0,lastHud=0;
let settings={muted:false,music:.025,reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches};try{settings={...settings,...JSON.parse(localStorage.getItem('dawn-settings')||'{}')};}catch{}
const keys=new Set(),pressed=new Set(),canvas=$('game'),ctx=canvas.getContext('2d');
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3800);}
function saveSettings(){try{localStorage.setItem('dawn-settings',JSON.stringify(settings));}catch{}document.body.classList.toggle('reduced-motion',!!settings.reducedMotion);}
async function api(path,data){const res=await fetch('/api/'+path,{method:data?'POST':'GET',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});let body;try{body=await res.json();}catch{throw Error('个人存档服务尚未连接，请从 Node 服务器打开游戏。');}if(!res.ok)throw Error(body.error||'操作未完成');if('user'in body){user=body.user;profile=P.normalizeProfile(body.profile);updateProfile();}return body;}
async function refreshProfile(){try{await api('me');}catch{$('save-status').textContent='存档服务未连接 · 可进行个人练习';}}
function updateProfile(){$('account-btn').textContent=user?user.username+' · 个人资料':'登录 / 存档';$('coin-count').textContent=profile.coins+' 金币';$('save-status').textContent=user?'服务器个人存档 · '+user.username:'访客模式 · 登录后保存联网成长';$('roster-summary').innerHTML=['Asuka','Rei'].map(c=>`<div class="roster-row"><span class="unit-thumb ${c==='Asuka'?'red':'blue'}"></span><div><strong>${names[c]} · Lv.${level(c)}</strong><small>熟练度 ${profile.characters[c].xp} · 已点亮 ${profile.characters[c].nodes.length} 个节点</small></div></div>`).join('');$('campaign-preview').innerHTML=Array.from({length:4},(_,i)=>`<div class="campaign-card"><strong>0${i+1}</strong><b>${['旧日清晨','河岸防线','纵深行动','黎明之战'][i]}</b><br><small>${i+1}-1 → ${i+1}-3 · 三阶段作战</small></div>`).join('');if(screen==='shop')renderShop();if(screen==='supply')renderSupply();if(screen==='room')renderRoomLoadout();applyAppearance();}
const level=c=>1+Math.floor(profile.characters[c].xp/300);
function icon(kind,c='Asuka'){return kind==='special'&&c==='Rei'?'blink':kind==='ultimate'&&c==='Rei'?'missile':kind;}
function modal(html){$('modal-body').innerHTML=html;$('modal').showModal();} $('close-modal').onclick=()=>$('modal').close();
function show(name){keys.clear();pressed.clear();if(game?.status==='playing'&&name!=='play'){if(game.online)sendNet({type:'pause',paused:true});else game.status='paused';}for(const s of document.querySelectorAll('.screen'))s.hidden=s.id!==name;screen=name;const current=$(name);current.classList.remove('screen-enter');void current.offsetWidth;current.classList.add('screen-enter');document.querySelectorAll('[data-screen]').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));document.querySelectorAll('.return-room').forEach(b=>b.hidden=!net);if(name==='home')updateProfile();if(name==='skills'){draft=[...(trial?trialBuilds[treeCharacter]:profile.characters[treeCharacter].nodes)];renderTree();}if(name==='shop')renderShop();if(name==='supply')renderSupply();if(name==='practice')document.querySelectorAll('[data-practice-char]').forEach(b=>b.classList.toggle('active',b.dataset.practiceChar===practiceCharacter));if(name==='room')renderRoomLoadout();window.scrollTo(0,0);}
document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>show(b.dataset.screen));$('brand').onclick=e=>{e.preventDefault();show('home');};document.querySelectorAll('.return-room').forEach(b=>b.onclick=()=>{show('room');});
// Account and persistent player profile.
function account(){if(!user){modal(`<h2>驾驶员档案</h2><p>两个人各建一个账号，保存自己的熟练度、技能树、金币与装备。</p><form id="auth-form" class="auth-form"><label>驾驶员代号<input name="username" minlength="3" maxlength="20" autocomplete="username" required></label><label>密码<input name="password" type="password" minlength="8" maxlength="72" autocomplete="current-password" required></label><div class="auth-buttons"><button type="submit" class="primary">登录档案</button><button type="button" id="register-account">创建新档案</button></div><span id="auth-message" role="status"></span><p>代号 3–20 字符，密码至少 8 位；你的密码不会显示给队友。</p></form>`);const form=$('auth-form');async function submit(type){if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));try{await api(type,data);$('modal').close();toast('档案已连接。');}catch(e){$('auth-message').textContent=e.message;}}form.onsubmit=e=>{e.preventDefault();submit('login');};$('register-account').onclick=()=>submit('register');return;}
 modal(`<h2>${esc(user.username)} 的个人资料</h2><p>熟练度、金币、技能与配件由服务器保存。</p><label>机库看板<select id="appearance-pilot"><option value="Asuka" ${profile.appearance?.pilot==='Asuka'?'selected':''}>明日香</option><option value="Rei" ${profile.appearance?.pilot==='Rei'?'selected':''}>绫波丽</option></select></label><p><label><input id="appearance-motion" type="checkbox" ${profile.appearance?.reducedMotion?'checked':''}> 减少动态效果</label></p><button id="save-appearance" class="primary">保存个人展示</button><button id="logout-account">退出档案</button>`);
 $('save-appearance').onclick=async()=>{try{await api('appearance',{pilot:$('appearance-pilot').value,reducedMotion:$('appearance-motion').checked});toast('个人展示已保存。');$('modal').close();}catch(e){toast(e.message);}};$('logout-account').onclick=async()=>{if(net){toast('请先离开当前小队再退出档案。');return;}try{await api('logout',{});$('modal').close();}catch(e){toast(e.message);}};
}
$('account-btn').onclick=account;
function applyAppearance(){const c=profile.appearance?.pilot||'Asuka';document.body.dataset.pilot=c;document.body.classList.toggle('reduced-motion',settings.reducedMotion||!!profile.appearance?.reducedMotion);const p=$('pilot-display'),m=$('mecha-display');if(p){p.src=`assets/pilot-${c.toLowerCase()}.png`;p.alt=names[c]+' 看板立绘';}if(m){m.src=`assets/mecha-${c.toLowerCase()}.png`;m.alt=names[c]+' 对应机体';}}
// Branching skill tree. Trial builds never overwrite sortie saves.
function renderTree(){const xp=trial?3000:profile.characters[treeCharacter].xp,lv=1+Math.floor(xp/300);$('tree-summary').textContent=`${trial?'试配模式':names[treeCharacter]+' · 熟练 Lv.'+lv} / 可用技能点 ${lv-draft.length}`;document.querySelectorAll('[data-tree]').forEach(b=>b.classList.toggle('active',b.dataset.tree===treeCharacter));$('trial-mode').checked=trial;$('save-tree').textContent=trial?'应用到个人练习':'保存出战配置';const defs=P.TREES[treeCharacter],branches=[...new Set(defs.map(n=>n.branch))];$('skill-tree').innerHTML=branches.map(branch=>`<div class="skill-branch"><h3>${esc(branch)}</h3>${defs.filter(n=>n.branch===branch).map(n=>{let locked='';try{P.validateBuild(treeCharacter,[...draft,n.id],xp);}catch(e){locked=e.message;}return `<button class="skill-node ${draft.includes(n.id)?'learned':''} ${locked?'locked':''} ${selectedNode===n.id?'selected':''}" data-node="${n.id}"><span class="skill-icon ${icon(n.icon,treeCharacter)}"></span><span class="node-copy"><b>${n.name}</b><small>${n.tier===3?'终极分支 · 互斥':'前置 '+(n.requires.length?'上一节点':'无')} · 熟练 Lv.${n.level}</small><em>${draft.includes(n.id)?'已点亮':locked||'可解锁 · 1 技能点'}</em></span></button>`;}).join('')}</div>`).join('');renderNodeDetail();}
function renderNodeDetail(){const n=P.TREES[treeCharacter].find(n=>n.id===selectedNode);if(!n){$('skill-detail').innerHTML='<div><h3>选择一个节点，查看它如何改变战斗。</h3><p>三条分支各有独立能力。终极节点只能选一条；可免费重置。</p></div>';return;}let error='';try{P.validateBuild(treeCharacter,[...draft,n.id],trial?3000:profile.characters[treeCharacter].xp);}catch(e){error=e.message;}$('skill-detail').innerHTML=`<div><h3>${n.name}</h3><p>${n.description}</p><span class="subtle">${error||'配置在下一次开局生效。'}</span></div><button id="learn-node" class="primary" ${draft.includes(n.id)||error?'disabled':''}>${draft.includes(n.id)?'已点亮':'点亮节点 · 1 点'}</button>`;if($('learn-node'))$('learn-node').onclick=()=>{draft=P.validateBuild(treeCharacter,[...draft,n.id],trial?3000:profile.characters[treeCharacter].xp);renderTree();};}
$('skill-tree').onclick=e=>{const b=e.target.closest('[data-node]');if(b){selectedNode=b.dataset.node;renderTree();}};document.querySelectorAll('[data-tree]').forEach(b=>b.onclick=()=>{if(trial)trialBuilds[treeCharacter]=draft;treeCharacter=b.dataset.tree;draft=[...(trial?trialBuilds[treeCharacter]:profile.characters[treeCharacter].nodes)];selectedNode=null;renderTree();});$('trial-mode').onchange=()=>{trial=$('trial-mode').checked;draft=[...(trial?trialBuilds[treeCharacter]:profile.characters[treeCharacter].nodes)];renderTree();};$('reset-tree').onclick=()=>{draft=[];renderTree();};$('save-tree').onclick=async()=>{if(trial){trialBuilds[treeCharacter]=[...draft];practiceCharacter=treeCharacter;toast('试配已应用，进入个人练习即可测试。');return;}if(!user){account();return;}try{await api('build',{character:treeCharacter,nodes:draft});if(net?.ready){net.ready=false;sendNet({type:'ready',ready:false});}toast('出战技能树已保存。');}catch(e){toast(e.message);}};
// Shop, equipment and selectable ammunition/melee.
function renderShop(){const c=$('equip-character').value,equipped=profile.equipment[c];$('equipment-slots').innerHTML=Object.entries(slots).map(([slot,name])=>`<div class="gear-slot"><small>${name}</small><b>${E.ITEMS.find(i=>i.id===equipped[slot])?.name||'基础配置'}</b>${equipped[slot]?`<button data-unequip="${slot}">卸下</button>`:''}</div>`).join('');$('shop-items').innerHTML=E.ITEMS.map(item=>{const owned=profile.inventory.includes(item.id),on=equipped[item.slot]===item.id;return `<div class="shop-item"><span class="skill-icon ${icon(item.icon,c)}"></span><h3>${item.name}</h3><p>${item.description}</p><span class="subtle">${slots[item.slot]} · ${owned?'已获得':'永久配件'}</span><div class="shop-price"><b>${item.price} 金币</b><button data-item="${item.id}" ${on?'disabled':''}>${on?'已装配':owned?'装配':'购买'}</button></div></div>`;}).join('');}
$('equip-character').onchange=renderShop;$('shop-items').onclick=async e=>{const b=e.target.closest('[data-item]');if(!b)return;if(!user){account();return;}const item=E.ITEMS.find(i=>i.id===b.dataset.item);try{if(profile.inventory.includes(item.id)){await api('equip',{character:$('equip-character').value,slot:item.slot,itemId:item.id});toast('配件已装配。');}else{await api('shop',{itemId:item.id});toast('购买成功，点击装配即可使用。');}if(net?.ready){net.ready=false;sendNet({type:'ready',ready:false});}renderShop();}catch(e){toast(e.message);}};$('equipment-slots').onclick=async e=>{const b=e.target.closest('[data-unequip]');if(!b)return;try{await api('equip',{character:$('equip-character').value,slot:b.dataset.unequip,itemId:null});renderShop();}catch(e){toast(e.message);}};
// Original sprite assets and new environmental textures.
const images={};let assetsReady=false,failedAssets=[];const needed=new Set(['map_1_18.png','map_1_01.png','map_1_14.png','map_1_54.png','dawn-courtyard.png','dawn-barricade.png','Boom.png']);for(const def of Object.values(A.images))if(def.file)needed.add(def.file);for(const dir of ['A','S','W'])needed.add(`TankEnemy_M${dir}_3.png`);
Promise.all([...needed].map(file=>new Promise(resolve=>{const img=new Image();img.onload=()=>{images[file]=img;resolve();};img.onerror=()=>{failedAssets.push(file);resolve();};img.src='assets/'+file;}))).then(()=>{assetsReady=true;if(failedAssets.length)console.warn('Optional sprite assets:',failedAssets);});
let audio=null,audioReady=false,musicTimer=null,musicStep=0;
function enableAudio(){try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume().then(()=>{audioReady=true;musicTimer ||= setInterval(music,420);}).catch(()=>{});}catch{}}
function music(){if(!audioReady||!audio||settings.muted||document.hidden)return;const notes=[261.63,329.63,392,329.63,293.66,349.23,440,349.23,246.94,293.66,392,293.66,261.63,329.63,523.25,392],t=audio.currentTime;for(const [f,gain,duration] of [[notes[musicStep%16],settings.music,.55],[musicStep%4===0?[130.81,146.83,123.47,130.81][Math.floor(musicStep/4)%4]:0,settings.music*.7,1.1]]){if(!f)continue;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.05);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+duration+.01);}musicStep++;}
function sound(kind){if(kind==='noenergy'){announce('同步能量不足');return;}if(settings.muted||!audioReady||audio?.state!=='running')return;const t=audio.currentTime,o=audio.createOscillator(),g=audio.createGain(),freq={fire:170,missile:90,hit:70,boom:40,heal:620,skill:400,win:880,melee:240}[kind]||240;o.type=['heal','skill','win'].includes(kind)?'sine':'triangle';o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(25,freq*.45),t+.13);g.gain.setValueAtTime(.035,t);g.gain.exponentialRampToValueAtTime(.001,t+.16);o.connect(g).connect(audio.destination);o.start(t);o.stop(t+.17);}
$('settings-btn').onclick=()=>{modal(`<h2>链路设置</h2><p><label><input id="mute-setting" type="checkbox" ${settings.muted?'checked':''}>关闭音乐与音效</label></p><label>配乐音量 <input id="music-setting" type="range" min="0" max="100" value="${Math.round(settings.music/.0005)}"></label><p><label><input id="motion-setting" type="checkbox" ${settings.reducedMotion?'checked':''}>减少动态效果与屏幕震动</label></p><p class="subtle">音乐在首次点击出击后启用；所有显示设置自动保存。</p>`);$('mute-setting').onchange=e=>{settings.muted=e.target.checked;saveSettings();if(!settings.muted)enableAudio();};$('music-setting').oninput=e=>{settings.music=Number(e.target.value)*.0005;saveSettings();};$('motion-setting').onchange=e=>{settings.reducedMotion=e.target.checked;saveSettings();};};
function held(...codes){return codes.some(c=>keys.has(c)||pressed.has(c));}function controls(){const dirs=['ArrowUp','ArrowRight','ArrowDown','ArrowLeft'];let dir=-1;for(const k of new Set([...keys,...pressed]))if(dirs.includes(k))dir=dirs.indexOf(k);return {dir,fire:held('Space'),heal:held('KeyE'),speed:held('KeyQ'),special:held('KeyW','KeyZ'),ultimate:held('KeyR','KeyX'),melee:held('KeyF'),item:held('KeyC'),ammo:held('Digit1')?'AP':held('Digit2')?'HE':held('Digit3')?'HESH':undefined};}
const gameKeys=new Set(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft','Space','KeyE','KeyQ','KeyW','KeyR','KeyZ','KeyX','KeyF','KeyC','Digit1','Digit2','Digit3']);window.addEventListener('keydown',e=>{if(screen!=='play'||$('modal').open)return;if(e.code==='Escape'){e.preventDefault();game?.status==='paused'?resume():pause();return;}if(game?.status!=='playing')return;if(gameKeys.has(e.code)){e.preventDefault();keys.add(e.code);pressed.add(e.code);}});window.addEventListener('keyup',e=>keys.delete(e.code));function blurGame(){keys.clear();pressed.clear();if(game?.online)sendNet({type:'input',input:{}});else pause();}window.addEventListener('blur',blurGame);document.addEventListener('visibilitychange',()=>{if(document.hidden)blurGame();});
function overlay(title,text,buttons){$('game-overlay').hidden=false;$('game-overlay').innerHTML=`<div class="overlay-card"><span class="eyebrow">SYNCHRONIZATION SYSTEM</span><h2>${esc(title)}</h2><p>${esc(text)}</p>${buttons.map(([a,t],i)=>`<button data-action="${a}" class="${i?'':'primary'}">${t}</button>`).join('')}</div>`;$('game-overlay').querySelector('button')?.focus();}
function pause(){if(!game||game.status!=='playing')return;keys.clear();pressed.clear();if(game.online){sendNet({type:'pause',paused:true});return;}game.status='paused';overlay('模拟暂停','准备好后继续训练。',[['resume','继续训练'],['reset','重置训练'],['practice','离开模拟舱']]);}
function resume(){if(game?.online){sendNet({type:'pause',paused:false});return;}game.status='playing';$('game-overlay').hidden=true;canvas.focus();enableAudio();} $('pause-btn').onclick=()=>game?.status==='paused'?resume():pause();
function startPractice(withTutorial=false){if(!assetsReady){toast('正在载入机体素材，请稍候。');return;}if(net){toast('请先离开联网小队。');return;}const m=D.blankMap(20,16);m.name=withTutorial?'初次同步 · 新手引导':'个人模拟舱';m.spawns=[{x:7,y:11},{x:9,y:11}];m.enemies=[{x:7,y:7,type:1},{x:10,y:7,type:2},{x:13,y:7,type:3}];m.tiles[9][4]=m.tiles[9][15]=2;m.tiles[6][5]=m.tiles[6][15]=2;game=new D.Game(m,{practice:true,character:practiceCharacter,nodes:{[practiceCharacter]:trial?trialBuilds[practiceCharacter]:profile.characters[practiceCharacter].nodes},gear:{[practiceCharacter]:Object.values(profile.equipment[practiceCharacter]).filter(Boolean)},loadouts:profile.loadouts});game.setPracticeOptions({invincible:true,noCooldown:$('no-cooldown').checked});if(withTutorial)game.players[0].hp-=30;tutorial=withTutorial?{step:0,completed:false}:null;rewarded=false;show('play');game.status='playing';$('game-overlay').hidden=true;$('practice-reset').hidden=false;$('battle-name').textContent=m.name;$('battle-mode').textContent='SIMULATION / '+names[practiceCharacter]+(trial?' / 技能自由试配':'');$('tutorial-panel').hidden=!withTutorial;canvas.focus();enableAudio();renderHud();}
$('start-practice').onclick=()=>startPractice(false);$('start-tutorial').onclick=$('tutorial-home').onclick=()=>startPractice(true);document.querySelectorAll('[data-practice-char]').forEach(b=>b.onclick=()=>{practiceCharacter=b.dataset.practiceChar;document.querySelectorAll('[data-practice-char]').forEach(el=>el.classList.toggle('active',el===b));});$('practice-reset').onclick=()=>{game?.resetPractice?.({resetStats:true});if(tutorial){tutorial={step:0,completed:false};game.players[0].hp-=30;}toast('训练统计与木桩已重置。');};
const tutorialSteps=[['机体响应','按方向键移动，让机体行进一段距离。',s=>s.moved>80],['主武器校准','朝上方木桩开火。按住空格，累计发射 3 次。',s=>s.shots>=3],['推进测试','按 Q 激活推进，观察蓝色尾迹和冷却图标。',s=>(s.skillUses?.speed||0)>0],['核心技能','按 W 使用角色核心技能：双炮压制 / 相位跃迁。',s=>(s.skillUses?.special||0)>0],['同步爆发','按 R 激活 A.T. 力场 / 发射导弹。',s=>(s.skillUses?.ultimate||0)>0],['近战与维护','接近木桩按 F 近战；按 E 修复预设受损机体。',s=>(s.heals||0)>0&&(s.melee||0)>0]];
function updateTutorial(){if(!tutorial||tutorial.completed||!game?.practice)return;const s=game.players[0].stats;if(tutorialSteps[tutorial.step][2](s)){tutorial.step++;sound('heal');}if(tutorial.step>=tutorialSteps.length){tutorial.completed=true;$('tutorial-title').textContent='同步完成。欢迎成为驾驶员。';$('tutorial-desc').textContent='你已掌握基础操作。联网时靠近倒地队友 3 秒救援；接力命中触发协同，支援技能可保护队友。';$('tutorial-progress').textContent='6 / 6 · 可继续自由练习';if(user)api('tutorial',{complete:true}).catch(e=>toast(e.message));return;}const [title,desc]=tutorialSteps[tutorial.step];$('tutorial-title').textContent=`0${tutorial.step+1} / ${title}`;$('tutorial-desc').textContent=desc;$('tutorial-progress').textContent=`${tutorial.step+1} / 6`;
}
const formatTime=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function finish(){if(rewarded)return;rewarded=true;keys.clear();pressed.clear();const won=game.status==='won',lastMission=net?.mission===3&&net?.stage===2;const buttons=[];if(net?.slot===0){if(won&&!lastMission)buttons.push(['next','下一小关 →']);buttons.push(['retry','再次挑战']);}buttons.push(['room','返回战前准备'],['leave','离开小队']);overlay(lastMission&&won?'我们终于走到了黎明':won?'作战完成':'机体信号中断',won?'熟练度、金币与作战记录已由服务器结算到登录驾驶员的档案。':'本次作战结束。调整配置，再一起出发。',buttons);const table=document.createElement('div');table.className='combat-stats';table.innerHTML='<table><tr><th>驾驶员</th><th>伤害</th><th>命中</th><th>救援</th><th>协同</th></tr>'+game.players.map(p=>`<tr><td>${names[p.character]}</td><td>${Math.round(p.stats.damage)}</td><td>${p.stats.shots?Math.round(p.stats.hits/p.stats.shots*100):0}%</td><td>${p.stats.rescues}</td><td>${p.stats.assists}</td></tr>`).join('')+'</table>';$('game-overlay').querySelector('.overlay-card p').after(table);sound(won?'win':'boom');refreshProfile();}
$('game-overlay').onclick=e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(a==='resume')resume();else if(a==='reset'){game.resetPractice({resetStats:true});resume();}else if(a==='practice'){game=null;tutorial=null;show('practice');}else if(a==='leave'){leaveOnline();show('home');}else if(a==='room'){show('room');}else if(a==='next'||a==='retry')sendNet({type:a});};

function drawImage(file,x,y,w,h){const img=images[file];if(img?.naturalWidth){ctx.drawImage(img,x,y,w,h);return true;}return false;}
function tileDraw(c,t,x,y,size){const f=t===1?'map_1_01.png':t===3?'map_1_14.png':t===4?'map_1_54.png':t===5?'dawn-courtyard.png':'map_1_18.png';if(images[f])c.drawImage(images[f],x,y,size,size);else{c.fillStyle=['#627729','#3d99ac','#5b6463','#a99355','#a58443','#757362'][t];c.fillRect(x,y,size,size);}if(t===2&&images['dawn-barricade.png']){c.drawImage(images['dawn-barricade.png'],x,y,size,size);}else if(t===2){c.fillStyle='#394745';c.fillRect(x+2,y+3,size-4,size-5);c.strokeStyle='#68716b';c.lineWidth=2;c.strokeRect(x+3,y+3,size-6,size-6);c.beginPath();c.moveTo(x+size/2,y+4);c.lineTo(x+size/2,y+size-4);c.moveTo(x+3,y+size/2);c.lineTo(x+size-3,y+size/2);c.stroke();}}
let terrain=null;function bakeTerrain(){terrain=document.createElement('canvas');terrain.width=game.map.width*60;terrain.height=game.map.height*60;const c=terrain.getContext('2d');c.imageSmoothingEnabled=false;game.map.tiles.forEach((row,y)=>row.forEach((t,x)=>tileDraw(c,t,x*60,y*60,60)));}
function sprite(a,x,y){
 const dir=a.dir===0?'W':a.dir===2?'S':'A',motion=a.firePose>0?'F':a.moving?'M':'S';
 let animName=a.team?`TankPlayer${a.character}_${motion}${dir}`:`TankEnemy_${motion}${dir}_${a.type}`;
 if(a.team&&a.heal>0)animName=`TankSkillHeal${a.character}_${dir}`;
 if(a.team&&a.character==='Asuka'&&a.shield>0)animName=`Asuka_${motion}${dir}`;
 const animation=A.animations[animName],def=animation&&A.images[animation.image];
 let img=def&&images[def.file],cw=def?.w||60,ch=def?.h||60,frames=animation?.frames||[0],dur=animation?.time||.3;
 if(!img){const fallback=a.team?`TankPlayer${a.character}_M${dir}.png`:`TankEnemy_M${dir}_${a.type}.png`;img=images[fallback];cw=ch=60;frames=[0,1,2];}
 const frame=frames[Math.floor(clock/Math.max(.03,dur/frames.length))%frames.length]||0;
 ctx.save();ctx.translate(x,y);if(a.dir===1)ctx.scale(-1,1);if(a.hp<=0)ctx.globalAlpha=.25;if(a.flash>0)ctx.globalAlpha=.5+.5*Math.sin(clock*45);
 if(img){const columns=Math.max(1,Math.floor(img.width/cw)),maxFrame=Math.floor(img.width/cw)*Math.floor(img.height/ch);const fr=frame%Math.max(1,maxFrame);ctx.drawImage(img,(fr%columns)*cw,Math.floor(fr/columns)*ch,cw,ch,-30,-30,60,60);}else{ctx.fillStyle=a.team?'#bf4e4c':'#858066';ctx.fillRect(-18,-22,36,44);}
 ctx.restore();
 if(a.team&&(a.shield>0||a.boost>0)){ctx.strokeStyle=a.shield>0?'#ffe098':'#8ccfff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,29,0,Math.PI*2);ctx.stroke();}
 if(a.hp>0){ctx.fillStyle='#142020dd';ctx.fillRect(x-22,y-37,44,4);ctx.fillStyle=a.team?(a.character==='Asuka'?'#f08b78':'#a6d6eb'):'#e3bf69';ctx.fillRect(x-22,y-37,44*a.hp/a.maxHp,4);}else if(a.team){ctx.fillStyle='#ffdb83';ctx.font='12px sans-serif';ctx.textAlign='center';ctx.fillText(a.revive>0?`救援 ${Math.ceil(3-a.revive)}s`:'靠近救援',x,y-30);}
}
let visualPositions=new Map(),visualDt=1/60;
function visual(a){if(!game.online)return a;let p=visualPositions.get(a.id);if(!p||Math.hypot(p.x-a.x,p.y-a.y)>180){p={x:a.x,y:a.y};visualPositions.set(a.id,p);}const blend=1-Math.exp(-24*visualDt);p.x+=(a.x-p.x)*blend;p.y+=(a.y-p.y)*blend;return {...a,x:p.x,y:p.y};}
function view(player,vx,vy,vw,vh){
 const cameraPlayer=visual(player);
 const mw=game.map.width*60,mh=game.map.height*60,cx=D.clamp(cameraPlayer.x-vw/2,0,Math.max(0,mw-vw)),cy=D.clamp(cameraPlayer.y-vh/2,0,Math.max(0,mh-vh));
 ctx.save();ctx.beginPath();ctx.rect(vx,vy,vw,vh);ctx.clip();ctx.translate(vx-cx,vy-cy);ctx.drawImage(terrain,0,0);
 for(const p of game.players)if(p.hp<=0){const v=visual(p);sprite(p,v.x,v.y);}
 for(const a of [...game.enemies,...game.players])if(a.hp>0){const v=visual(a);sprite(a,v.x,v.y);}
 for(const raw of game.bullets){const b=visual(raw);ctx.fillStyle=b.missile?'#fbeec3':b.ammo==='HE'?'#ffab6b':b.ammo==='HESH'?'#c7a3fc':b.team?'#b0e9ff':'#ff7464';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=5;ctx.beginPath();ctx.ellipse(b.x,b.y,b.r,b.missile?b.r*1.6:b.r,0,0,7);ctx.fill();ctx.shadowBlur=0;}
 for(const e of game.effects)drawFX(e);ctx.globalAlpha=1;

 ctx.restore();
 const miniW=120,miniH=120*game.map.height/game.map.width,mx=vx+vw-miniW-12,my=vy+12;
 ctx.fillStyle='#091411ce';ctx.fillRect(mx-3,my-3,miniW+6,miniH+6);ctx.globalAlpha=.8;ctx.drawImage(terrain,mx,my,miniW,miniH);ctx.globalAlpha=1;for(const a of [...game.enemies,...game.players])if(a.hp>0){ctx.fillStyle=a.team?(a===player?'#fff':'#75d8ff'):'#ff5248';ctx.fillRect(mx+a.x/mw*miniW-2,my+a.y/mh*miniH-2,4,4);}ctx.strokeStyle='#fff9';ctx.strokeRect(mx+cx/mw*miniW,my+cy/mh*miniH,vw/mw*miniW,vh/mh*miniH);
 ctx.font='bold 12px sans-serif';ctx.fillStyle='#fff';ctx.textAlign='left';ctx.fillText(names[player.character],vx+12,vy+22);
}
let bakedFor=null;function render(dt=1/60){if(!game)return;visualDt=dt;if(bakedFor!==game){bakeTerrain();visualPositions.clear();bakedFor=game;}ctx.imageSmoothingEnabled=false;ctx.fillStyle='#18221a';ctx.fillRect(0,0,canvas.width,canvas.height);if(game.online){view(game.players[net?.slot||0],0,0,canvas.width,canvas.height);}else if(game.coop){view(game.players[0],0,0,498,600);view(game.players[1],502,0,498,600);ctx.fillStyle='#10191e';ctx.fillRect(498,0,4,600);}else view(game.players[0],0,0,canvas.width,canvas.height);}
function drawFX(e){const progress=1-e.life/e.max,r=e.radius||40;ctx.save();ctx.translate(e.x,e.y);ctx.globalAlpha=Math.max(0,e.life/e.max);let color=['heal'].includes(e.kind)?'#a0f0c0':['shield','teleport','combo'].includes(e.kind)?'#96ddff':e.kind==='armorbreak'?'#d6a2ff':'#ffc67a';ctx.strokeStyle=color;ctx.fillStyle=color;ctx.lineWidth=2;
 if(e.kind==='impact'){ctx.font='bold 13px sans-serif';ctx.textAlign='center';ctx.fillStyle=e.label==='背部命中'?'#fff0a4':e.label==='共振破甲'?'#d4acff':'#dcefff';ctx.fillText(`${e.label||'命中'} ${Math.round(e.amount||0)}`,0,-26-progress*25);}
 else if(['boom','missile','explosion'].includes(e.kind)){const img=images['Boom.png'];if(img){const cw=60,cols=Math.max(1,Math.floor(img.width/cw)),frames=cols*Math.floor(img.height/60),i=Math.min(frames-1,Math.floor(progress*frames));ctx.drawImage(img,(i%cols)*60,Math.floor(i/cols)*60,60,60,-r/2,-r/2,r,r);}ctx.beginPath();ctx.arc(0,0,Math.max(3,r*progress),0,7);ctx.stroke();}
 else if(e.kind==='shield'){ctx.rotate(Math.PI/6+progress*.15);ctx.lineWidth=3;for(const scale of [1,.84]){ctx.beginPath();for(let i=0;i<=6;i++){const a=i*Math.PI/3;const x=Math.cos(a)*r*scale,y=Math.sin(a)*r*scale;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.stroke();}}
 else if(e.kind==='slash'||e.kind==='spear'){const a=(e.dir??0)*Math.PI/2-Math.PI/2;ctx.rotate(a);ctx.lineWidth=5;if(e.kind==='slash'){ctx.beginPath();ctx.arc(0,0,r*.8,-1+progress*.4,1-progress*.4);ctx.stroke();}else{ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(r,0);ctx.lineTo(r-15,-8);ctx.moveTo(r,0);ctx.lineTo(r-15,8);ctx.stroke();}}
 else if(e.kind==='heal'){for(let i=0;i<5;i++){const a=i*1.26;const x=Math.cos(a)*r*.25,y=Math.sin(a)*r*.25-progress*22;ctx.fillRect(x-5,y-1,10,2);ctx.fillRect(x-1,y-5,2,10);}ctx.beginPath();ctx.ellipse(0,15,r*.45,r*.16,0,0,7);ctx.stroke();}
 else if(e.kind==='teleport'){for(let i=0;i<3;i++){ctx.beginPath();ctx.ellipse(0,0,r*(.35+progress*.5+i*.15),r*(.12+i*.04),progress*.4,0,7);ctx.stroke();}}
 else{ctx.beginPath();ctx.arc(0,0,Math.max(3,progress*r),0,7);ctx.stroke();}ctx.restore();}
function renderHud(){if(!game)return;const p=game.players[game.online?net?.slot||0:0],friend=game.players.find(a=>a!==p),defs=[['fire','主武器','空格',1],['heal','修复','E',20],['speed','推进','Q',15],['special',p.character==='Asuka'?'双炮压制':'相位跃迁','W',5],['ultimate',p.character==='Asuka'?'A.T. 觉醒':'导弹打击','R',10],['melee','近战','F',1],['item','主动配件','C',30]];
 $('battle-stats').textContent=game.practice?`${formatTime(game.time)} · 伤害 ${Math.round(p.stats.damage)} · DPS ${(p.stats.damage/Math.max(1,game.time)).toFixed(1)} · 命中 ${p.stats.shots?Math.round(p.stats.hits/p.stats.shots*100):0}%`:`${formatTime(game.time)} · 敌机 ${game.enemies.filter(e=>e.hp>0).length} / ${game.enemies.length} · ${game.score} 分 · ${net?.latency??0} ms`;
 $('player-hud').innerHTML=`<div class="hud-pilot"><h3>${names[p.character]} <small>${game.online?'你的机体':'训练机体'}</small></h3><div class="hp ${p.character==='Rei'?'blue':''}"><span style="width:${100*p.hp/p.maxHp}%"></span></div><small>HP ${Math.ceil(p.hp)} / ${p.maxHp} · ${p.loadout?.ammo||'AP'} 弹种</small><div class=energy><span style="width:${p.energy??100}%"></span></div><small>同步能量 ${Math.floor(p.energy??100)} / 100</small></div><div class="hud-skills">${defs.map(([key,name,kbd,max])=>{const cd=p.cd[key]||0;return `<div><button class="ability ${cd<=0?'ready':''}" data-ability="${key}" title="${name} · ${kbd}${cd>0?' · 冷却 '+cd.toFixed(1)+' 秒':''}" aria-label="${name}，按 ${kbd}，${cd>0?'冷却中':'已就绪'}"><span class="skill-icon ${key==='melee'?'fire':key==='item'?'heal':icon(key,p.character)}"><span class="cd-mask" style="height:${Math.min(100,cd/max*100)}%"></span></span>${cd>0?`<span class="cd-number">${Math.ceil(cd)}</span>`:''}<kbd>${kbd}</kbd></button><div class="hud-skill-label">${name}</div></div>`;}).join('')}</div><div class="hud-teammate">${friend?`<b>${names[friend.character]} · 队友</b><div class="hp ${friend.character==='Rei'?'blue':''}"><span style="width:${100*friend.hp/friend.maxHp}%"></span></div><small>${friend.hp>0?'信号在线':'信号微弱 · 靠近救援'}<br>协同 ${p.stats.assists} · 救援 ${p.stats.rescues}</small>`:`<b>模拟舱状态</b><small>木桩无限重生<br>F 近战 · 免费测试</small>`}</div>`;
 if(game.effects.some(e=>e.kind==='combo'))announce('双机共鸣 · 协同命中');
}
$('player-hud').onclick=e=>{const b=e.target.closest('[data-ability]');if(!b||game?.status!=='playing')return;const key=b.dataset.ability;if(game.online){const input=controls();input[key]=true;sendNet({type:'input',input});}else if(key==='fire'){pressed.add('Space');}else if(key==='melee'){pressed.add('KeyF');}else if(key==='item'){pressed.add('KeyC');}else game.skill(game.players[0],key);canvas.focus();};
let announcementTimer;function announce(text){$('combat-announcement').textContent=text;clearTimeout(announcementTimer);announcementTimer=setTimeout(()=>$('combat-announcement').textContent='',1500);}
function frame(time){const dt=Math.min(.05,(time-last)/1000||0);last=time;clock+=dt;if(screen==='play'&&game){if(game.status==='playing'&&!game.online){game.step(dt,[controls()]);pressed.clear();game.events.slice(0,4).forEach(sound);updateTutorial();}render(dt);if(time-lastHud>120){renderHud();lastHud=time;}}requestAnimationFrame(frame);}requestAnimationFrame(frame);
// Server-owned rooms and pre-sortie preparation.
function sendNet(m){if(net?.ws?.readyState===1)net.ws.send(JSON.stringify(m));}function leaveOnline(){if(!net)return;const old=net;sendNet({type:'leave'});net=null;clearInterval(old.inputTimer);clearInterval(old.pingTimer);clearTimeout(old.reconnectTimer);old.ws?.close();if(game?.online)game=null;keys.clear();pressed.clear();$('create-room').disabled=$('join-room').disabled=false;}
function roomCharacter(){return net?.character||'Asuka';}
function renderRoomLoadout(){if(!net)return;const c=roomCharacter(),u=profile.characters[c];document.querySelectorAll('[data-choose]').forEach(b=>b.classList.toggle('active',b.dataset.choose===c));$('room-loadout').innerHTML=`<div class="loadout-block"><b>熟练等级 Lv.${level(c)} · ${u.xp} 熟练度</b><small>技能树 ${u.nodes.map(id=>P.TREES[c].find(n=>n.id===id)?.name).filter(Boolean).join(' / ')||'基础同步配置'}</small></div><div class="loadout-block"><b>装备</b><small>${Object.values(profile.equipment[c]).map(id=>E.ITEMS.find(i=>i.id===id)?.name).filter(Boolean).join(' / ')||'基础机体 · 无额外配件'}</small></div><div class="loadout-block"><label>远程弹种<select id="loadout-ammo"><option value="AP">阳电子穿甲弹 · 精确直击</option><option value="HE">N² 高爆弹 · 范围爆破</option><option value="HESH">共振碎甲弹 · 防护削弱</option></select></label><label>近战武器<select id="loadout-melee"><option value="blade">高振动刀刃 · 扇形斩击</option><option value="spear">相位长矛 · 远距突刺</option></select></label><button id="save-loadout">保存武器配置</button></div>`;$('loadout-ammo').value=profile.loadouts?.[c]?.ammo||'AP';$('loadout-melee').value=profile.loadouts?.[c]?.melee||'blade';$('save-loadout').onclick=async()=>{if(!user){account();return;}try{await api('loadout',{character:c,ammo:$('loadout-ammo').value,melee:$('loadout-melee').value});if(net?.ready){net.ready=false;sendNet({type:'ready',ready:false});}toast('武器配置已保存。');}catch(e){toast(e.message);}};$('ready-room').textContent=game?.online&&game.status==='playing'?'返回战场':net.ready?'取消准备':'我已准备';}
function connectOnline(initial){if(net){show(game?.online&&game.status==='playing'?'play':'room');return;}if(!/^https?:$/.test(location.protocol)){toast('联网需要从服务器网页打开，请运行 npm start。');return;}net={ws:null,slot:0,character:'Asuka',code:'',token:'',initial,ready:false,round:null,map:null,attempts:0,latency:0};$('network-status').textContent='正在建立链路…';$('create-room').disabled=$('join-room').disabled=true;connectSocket(net);}
function connectSocket(n){if(net!==n)return;const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws`);n.ws=ws;ws.onopen=()=>{if(net===n)sendNet(n.token?{type:'resume',code:n.code,token:n.token}:n.initial);};ws.onerror=()=>{};ws.onmessage=e=>{if(net!==n)return;let m;try{m=JSON.parse(e.data);}catch{return;}
 if(m.type==='error'){toast(m.message);$('network-status').textContent=m.message;if(!n.token){net=null;ws.close();$('create-room').disabled=$('join-room').disabled=false;}return;}
 if(m.type==='joined'){n.slot=m.slot;n.code=m.code;n.token=m.token;n.attempts=0;$('room-title').textContent=`小队 ${m.code} · ${m.slot?'队员':'房主'}`;$('invite-address').textContent=`邀请地址 ${location.origin}/?room=${m.code}`;show('room');return;}
 if(m.type==='lobby'){n.character=m.slots[n.slot]?.character||(n.slot?'Rei':'Asuka');n.ready=!!m.slots[n.slot]?.ready;n.mission=m.mission;n.stage=m.stage||0;n.difficulty=m.difficulty||'normal';$('online-mission').value=String(m.mission);$('online-stage').value=String(m.stage||0);$('difficulty').value=n.difficulty;for(const id of ['online-mission','online-stage','difficulty','configure-room'])$(id).disabled=n.slot!==0;$('room-players').innerHTML=m.slots.map((s,i)=>`<div class="squad-member ${s?.ready?'ready':''}"><b>${s?names[s.character]:'等待驾驶员'}${i===n.slot?' · 你':''}</b><small>${esc(s?.username||'临时访客')} · ${i?'队员':'房主'}</small><span>${!s?'等待加入':!s.connected?'断线 · 等待重连':s.ready?'同步就绪':'配置中'}</span></div>`).join('');$('mission-brief').textContent=`当前任务 ${m.mission+1}-${(m.stage||0)+1} · ${m.map||''} · ${n.difficulty==='hard'?'危机':n.difficulty==='relaxed'?'回忆':'标准'}难度`;renderRoomLoadout();return;}
 if(m.type==='start'){n.map=m.map;n.round=m.round;n.mission=m.mission;n.stage=m.stage||0;n.character=m.characters?.[n.slot]||n.character;rewarded=false;game=null;tutorial=null;keys.clear();pressed.clear();show('play');$('game-overlay').hidden=true;$('tutorial-panel').hidden=true;$('practice-reset').hidden=true;$('battle-name').textContent=`${m.mission+1}-${(m.stage||0)+1} / ${m.map.name}`;$('battle-mode').textContent=`ONLINE / ${names[n.character]} / 小队 ${n.code}`;canvas.focus();enableAudio();return;}
 if(m.type==='state'){if(!n.map)return;const previous=game?.status;if(!game||!game.online)game={...m.state,map:n.map,online:true};else Object.assign(game,m.state);const ids=new Set([...game.players,...game.enemies,...game.bullets].map(a=>a.id));for(const id of visualPositions.keys())if(!ids.has(id))visualPositions.delete(id);if(m.paused){if(previous!=='paused'||m.waiting!==n.waiting)overlay(m.waiting?'同步链路中断':'小队暂停',m.waiting?'等待队友恢复连接，座位保留 30 秒。':'任意驾驶员都可以继续作战。',m.waiting?[['leave','离开小队']]:[['resume','继续作战'],['leave','离开小队']]);}else if(previous==='paused'&&game.status==='playing'){$('game-overlay').hidden=true;canvas.focus();}n.waiting=m.waiting;if(game.status==='playing')game.events?.slice(0,3).forEach(sound);if(['won','lost'].includes(game.status))finish();return;}
 if(m.type==='pong'){n.latency=Math.max(0,Date.now()-Number(m.stamp));$('server-label').textContent=`指挥链路 ${n.latency} ms`;return;}
 if(m.type==='ended'){toast(m.message);leaveOnline();show('home');}
 };ws.onclose=()=>{if(net!==n)return;if(!n.token){net=null;$('network-status').textContent='房间服务器未连接，请确认 npm start 正在运行。';$('create-room').disabled=$('join-room').disabled=false;return;}if(++n.attempts>12){toast('重连超时，请重新组队。');leaveOnline();show('home');return;}if(game?.online){game.status='paused';overlay('正在重建同步链路','自动重连中，服务器暂时保留你的座位。',[['leave','离开小队']]);}n.reconnectTimer=setTimeout(()=>connectSocket(n),1500);};
 if(!n.inputTimer)n.inputTimer=setInterval(()=>{if(net===n&&game?.online&&game.status==='playing'){sendNet({type:'input',input:screen==='play'&&!document.hidden?controls():{}});pressed.clear();}},50);if(!n.pingTimer)n.pingTimer=setInterval(()=>sendNet({type:'ping',stamp:Date.now()}),3000);
}
$('create-room').onclick=()=>connectOnline({type:'create'});$('join-room').onclick=()=>{const code=$('room-code').value.trim().toUpperCase();if(!/^[A-F0-9]{6}$/.test(code)){toast('请输入六位房间码。');return;}connectOnline({type:'join',code});};$('leave-room').onclick=()=>{leaveOnline();show('home');};$('configure-room').onclick=()=>sendNet({type:'configure',mission:Number($('online-mission').value),stage:Number($('online-stage').value),difficulty:$('difficulty').value});document.querySelectorAll('[data-choose]').forEach(b=>b.onclick=()=>sendNet({type:'choose',character:b.dataset.choose}));$('ready-room').onclick=()=>{if(!net)return;if(game?.online&&game.status==='playing'){show('play');return;}net.ready=!net.ready;sendNet({type:'ready',ready:net.ready});};$('room-skills').onclick=()=>{treeCharacter=roomCharacter();trial=false;show('skills');};$('room-equipment').onclick=()=>{$('equip-character').value=roomCharacter();show('shop');};
$('records-btn').onclick=()=>{const history=profile.records.history;modal(`<h2>驾驶员作战档案</h2><p>${profile.records.wins} 次胜利 / ${profile.records.losses} 次失利 · ${user?'服务器个人记录':'登录后保存联网记录'}</p>${history.length?`<table><tr><th>任务</th><th>角色</th><th>结果</th><th>熟练度</th><th>伤害</th></tr>${history.slice(0,15).map(r=>`<tr><td>${r.mission+1}-${(r.stage||0)+1}</td><td>${names[r.character]||''}</td><td>${r.won?'完成':'失利'}</td><td>+${r.xp||0}</td><td>${Math.round(r.stats?.damage||0)}</td></tr>`).join('')}</table>`:'<p>第一场并肩作战，正等待你们。</p>'}`);};$('credits-btn').onclick=()=>modal('<h2>从 2017，走向黎明</h2><p>原作：闫鑫 · 方铮辉。</p><p>最初是致敬《新世纪福音战士》的双人机器人作战项目。战斗精灵保留当年的红蓝机体，续作补上联网、成长与机甲指挥室。</p><img src="assets/Hello.png" alt="当年原始封面" style="width:100%;max-width:420px"><p class="subtle">原始素材保留；新机库、环境与看板图像为 2026 新增。配乐与音效由程序合成。</p>');
const invited=new URLSearchParams(location.search).get('room');if(invited&&/^[A-Fa-f0-9]{6}$/.test(invited)){$('room-code').value=invited.toUpperCase();toast('已填入朋友的房间码，点击加入。');}saveSettings();updateProfile();refreshProfile();
window.dawnSnapshot=()=>game?{status:game.status,practice:game.practice,online:game.online,time:game.time,players:game.players.map(p=>({character:p.character,x:p.x,y:p.y,hp:p.hp,stats:p.stats,loadout:p.loadout,cd:p.cd})),enemies:game.enemies.filter(e=>e.hp>0).length}:{status:screen,assetsReady,failedAssets};

function renderSupply(){$('supply-balance').textContent=`${profile.tickets||0} 张补给券 · 保底进度 ${profile.pity||0} / 10`;$('draw-supply').disabled=!!user&&(profile.tickets||0)<1;$('supply-pool').innerHTML=E.ITEMS.map(item=>`<div class="pool-row"><span class="skill-icon ${icon(item.icon)}"></span><div><b>${item.name}</b><small>${item.price>=180?'稀有 · 每件约 8.33%':'普通 · 每件 25%'}</small></div></div>`).join('');$('draw-history').innerHTML=(profile.drawHistory||[]).slice(0,6).map(r=>`<p class="subtle">${E.ITEMS.find(i=>i.id===r.itemId)?.name||'配件'}${r.duplicate?' · 重复转金币':''}</p>`).join('')||'<p class="subtle">还没有补给记录。</p>';}
$('draw-supply').onclick=async()=>{if(!user){account();return;}$('draw-supply').disabled=true;try{const result=await api('draw',{}),r=result.reward,item=E.ITEMS.find(i=>i.id===r.itemId);$('draw-result').innerHTML=`<div class="reward-card ${r.rarity==='rare'?'rare':''}"><span class="skill-icon ${icon(item.icon)}"></span><small>${r.pityTriggered?'保底信号已接收':r.rarity==='rare'?'稀有信号':'补给已到达'}</small><h3>${item.name}</h3><p>${r.duplicate?`重复奖励 · 已转换为 ${r.coins} 金币`:'已加入配件仓库，可在补给页装配。'}</p></div>`;sound('win');renderSupply();}catch(e){toast(e.message);$('draw-supply').disabled=false;}};

// Fixed 16:9 game client: never reflow or stretch the game to browser dimensions.
function fitClient(){const scale=Math.min(innerWidth/1600,innerHeight/900);$('game-client').style.setProperty('--client-scale',scale);}
window.addEventListener('resize',fitClient);fitClient();
$('home').addEventListener('pointermove',e=>{if(settings.reducedMotion||profile.appearance?.reducedMotion)return;const r=$('home').getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$('home').style.setProperty('--parallax-x',`${x*10}px`);$('home').style.setProperty('--parallax-y',`${y*7}px`);});$('home').addEventListener('pointerleave',()=>{$('home').style.setProperty('--parallax-x','0px');$('home').style.setProperty('--parallax-y','0px');});
